### ISSUE TITLE
Adding Remotec ZXT-120EU AC Extender

### ISSUE THREAD

**Issue by chrisboer** [TedTolboom/hk.com.remotec#19]
I needed to add / delete the device multiple times after about 8 times it finally was added.

By the way the Remotec remote was added in 2 seconds.. ;-)

**Comment by TedTolboom** [comment]
@chrisboer quite difficult to say what could have caused this...
Could be some congestion on the Z-wave network.

I don't expect that it is app related; the only contribution the app has to the inclusion process is to specify the device ID's. Since the last inclusion was working, the device ID's are correct.

I will monitor this for re-occurance, but also close this issue in the meanwhile.
If you see it re-occuring, please re-open this issue.
